### ISSUE TITLE
Develop a dropdown menu for each project (represented by the 3 dots icon) that contains various actions.

### ISSUE THREAD

**Issue by Ahmed-you** [Ahmed-you/Promengo#12]
-Details:
     - Actions should include: **Edit Project**, **Delete Project**, **View Project Details**.
     - On clicking **Edit**, a modal should appear to modify the project name.
     - On clicking **Delete**, the global warning note should appear to confirm deletion.

**Comment by MonkeyDluffySan** [comment]
it will be combined with issue number #9

**Comment by Ahmed-you** [comment]
it will be combined with issue number #9
